In [1]:
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

In [2]:
ds = pd.read_csv("data_set_6.csv")

In [3]:
ds.head()

Unnamed: 0      Company  fuel-type  num-of-doors  body-style  length  \
0           0  alfa-romero          1             2           1   168.8   
1           1  alfa-romero          1             2           1   168.8   
2           2  alfa-romero          1             2           2   171.2   
3           3         audi          1             4           3   176.6   
4           4         audi          1             4           3   176.6   

   num-of-cylinders  peak-rpm  city-mpg  highway-mpg    price  Gear-type  
0                 4      5000         9           11  1012125          1  
1                 4      5000         9           11  1237500          2  
2                 6      5000         8           11  1237500          1  
3                 4      5500        10           12  1046250          2  
4                 5      5500         7            9  1308750          1

In [4]:
#print(record['continent'].unique()) 
print(ds['Company'].unique())

['alfa-romero' 'audi' 'bmw' 'chevrolet' 'dodge' 'honda' 'isuzu' 'jaguar'
 'mazda' 'mercedes-benz' 'mercury' 'mitsubishi' 'nissan' 'peugot'
 'plymouth' 'porsche' 'renault' 'saab' 'subaru' 'toyota' 'volkswagen'
 'volvo']


In [5]:
predict_result={"alfa-romero" : "alfa-romero",
                "audi" : "audi",
                "bmw" : "bmw",
                "chevrolet" : "chevrolet",
                "dodge" : "dodge",
                "honda":"honda",
                "isuzu":"isuzu",
                "jaguar":"jaguar",
                "mazda":"mazda",
                "mercedes-benz":"mercedes-benz",
                "mercury":"mercury",
                "mitsubishi":"mitsubishi",
                "nissan":"nissan",
                "peugot":"peugot",
                "plymouth":"plymouth",
                "porsche":"porsche",
                "renault":"renault",
                "saab":"saab",
                "subaru":"subaru",
                "toyota":"toyota",
                "volkswagen":"volkswagen",
                "volvo":"volvo"}


In [6]:
print ("Dataset Length: ", len(ds)) 
print ("Dataset Shape: ", ds.shape) 

Dataset Length:  205
Dataset Shape:  (205, 12)


In [7]:
print ("Dataset: ",ds.head())

X = ds.values[:, 2:] 
Y = ds.values[:, 1] 
print(X)

Dataset:     Unnamed: 0      Company  fuel-type  num-of-doors  body-style  length  \
0           0  alfa-romero          1             2           1   168.8   
1           1  alfa-romero          1             2           1   168.8   
2           2  alfa-romero          1             2           2   171.2   
3           3         audi          1             4           3   176.6   
4           4         audi          1             4           3   176.6   

   num-of-cylinders  peak-rpm  city-mpg  highway-mpg    price  Gear-type  
0                 4      5000         9           11  1012125          1  
1                 4      5000         9           11  1237500          2  
2                 6      5000         8           11  1237500          1  
3                 4      5500        10           12  1046250          2  
4                 5      5500         7            9  1308750          1  
[[1 2 1 ... 11 1012125 1]
 [1 2 1 ... 11 1237500 2]
 [1 2 2 ... 11 1237500 1]
 ...
 [1 4 

In [8]:
print(Y)

['alfa-romero' 'alfa-romero' 'alfa-romero' 'audi' 'audi' 'audi' 'audi'
 'audi' 'audi' 'audi' 'bmw' 'bmw' 'bmw' 'bmw' 'bmw' 'bmw' 'bmw' 'bmw'
 'chevrolet' 'chevrolet' 'chevrolet' 'dodge' 'dodge' 'dodge' 'dodge'
 'dodge' 'dodge' 'dodge' 'dodge' 'dodge' 'honda' 'honda' 'honda' 'honda'
 'honda' 'honda' 'honda' 'honda' 'honda' 'honda' 'honda' 'honda' 'honda'
 'isuzu' 'isuzu' 'isuzu' 'isuzu' 'jaguar' 'jaguar' 'jaguar' 'mazda'
 'mazda' 'mazda' 'mazda' 'mazda' 'mazda' 'mazda' 'mazda' 'mazda' 'mazda'
 'mazda' 'mazda' 'mazda' 'mazda' 'mazda' 'mazda' 'mazda' 'mercedes-benz'
 'mercedes-benz' 'mercedes-benz' 'mercedes-benz' 'mercedes-benz'
 'mercedes-benz' 'mercedes-benz' 'mercedes-benz' 'mercury' 'mitsubishi'
 'mitsubishi' 'mitsubishi' 'mitsubishi' 'mitsubishi' 'mitsubishi'
 'mitsubishi' 'mitsubishi' 'mitsubishi' 'mitsubishi' 'mitsubishi'
 'mitsubishi' 'mitsubishi' 'nissan' 'nissan' 'nissan' 'nissan' 'nissan'
 'nissan' 'nissan' 'nissan' 'nissan' 'nissan' 'nissan' 'nissan' 'nissan'
 'nissan' 'nissa

In [9]:
# Spliting the dataset into train and test 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 100) 


In [10]:
model = DecisionTreeClassifier(criterion = "gini", random_state = 100,max_depth=3, min_samples_leaf=5) 

In [11]:
# Actual training process 
model.fit(X_train, y_train) 

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=100)

In [12]:
y_pred = model.predict(X_test) 
print("Predicted values:") 
print(y_pred)

Predicted values:
['toyota' 'dodge' 'toyota' 'honda' 'toyota' 'toyota' 'peugot' 'peugot'
 'peugot' 'toyota' 'audi' 'audi' 'peugot' 'mazda' 'peugot' 'honda'
 'toyota' 'audi' 'peugot' 'peugot' 'audi' 'audi' 'mazda' 'dodge' 'toyota'
 'nissan' 'peugot' 'peugot' 'mazda' 'toyota' 'dodge' 'audi' 'peugot'
 'audi' 'peugot' 'toyota' 'audi' 'toyota' 'nissan' 'toyota' 'peugot'
 'audi' 'toyota' 'toyota' 'dodge' 'nissan' 'dodge' 'dodge' 'toyota'
 'toyota' 'toyota' 'toyota' 'toyota' 'audi' 'audi' 'toyota' 'toyota'
 'toyota' 'peugot' 'toyota' 'mazda' 'mazda']


In [13]:
print("Confusion Matrix:\n ", confusion_matrix(y_test, y_pred)) 

Confusion Matrix:
  [[ 2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  1  0  0  0  0  1  0  0]
 [ 0  0  1  1  0  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  1  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  3  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  1  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  1  0  0  0  0 10  0  0]
 [ 1  0  1  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0]
 [ 4  0  0 

In [14]:
print ("Accuracy : ", accuracy_score(y_test,y_pred)*100) 

Accuracy :  32.25806451612903


In [15]:
print("Report : ", classification_report(y_test, y_pred))

Report :                 precision    recall  f1-score   support

         audi       0.18      1.00      0.31         2
          bmw       0.00      0.00      0.00         2
        dodge       0.17      0.33      0.22         3
        honda       0.50      0.25      0.33         4
        isuzu       0.00      0.00      0.00         1
        mazda       0.00      0.00      0.00         4
mercedes-benz       0.00      0.00      0.00         3
      mercury       0.00      0.00      0.00         1
   mitsubishi       0.00      0.00      0.00         4
       nissan       1.00      0.75      0.86         4
       peugot       0.23      1.00      0.38         3
     plymouth       0.00      0.00      0.00         3
      porsche       0.00      0.00      0.00         2
         saab       0.00      0.00      0.00         3
       subaru       0.00      0.00      0.00         1
       toyota       0.45      0.83      0.59        12
   volkswagen       0.00      0.00      0.00         5

C:\Users\DK\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
a=[]
a.append(int(input("body-style:")))
a.append(int(input("fuel-type :")))
a.append(int(input("price-range")))
a.append(int(input("city-mpg:")))
a.append(int(input("no.of.cylinders:")))
a.append(int(input("no.of.doors:")))
a.append(int(input("length:")))
a.append(int(input("peak-rpm:")))
a.append(int(input("highway-mpg:")))
a.append(int(input("Gear-type:")))

In [18]:
test_ip=[]
test_ip.append(a)

In [19]:
test_pred=model.predict(test_ip)

print(predict_result[test_pred[0]])

toyota
